title: Neil Patel
email: your-email@example.com
logo: "/assets/images/logo.svg"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

home:
  services:
    enabled: true
    background: "#fff"
    btnText: "yes, i want to <strong>work</strong> with <strong>neil</strong>"
    btnUrl: "#"
    heading: "<span>Need help</span> with implementing Software and Automating Business Process?"
    smallHeading: ""
    description: >
     All successful businesses in every industry are continually investing in improving their business processes and implementing software to stay current and get ahead of their competition.<br>
     
     Are you thinking of implementing a software into your business, or are you in the middle of a software project? Thinking of documenting or improving your business processes?<br>

     If either of those questions apply to you, book a 30 minute strategy call, and let's discuss how I can help. We will go over your current business and I will walk you through my methodology and how it can help you achieve your goals no matter where you are in the digital transformation journey.
    items:
    - heading: >
       <span> IT </span>       
       Strategy
      body: > 
        Are you looking to reinvent and strategically reposition your business in today’s digital economy? Are you aiming to align technology and operations with your business vision? I help business owners and executives develop a plan, and set goals for how technologies will be implemented and used to meet key business objectives. We will define and prioritize your IT initiatives, and outline steps you have to take to turn your vision into a reality. As a result you will have a well thought out technology program that, when executed, will help you drive value, achieve competitive advantages, and improve customer experiences. Book a call, and let's see how I can help!	
      icon: "/assets/images/search.png"
    - heading: >
       <span> Business</span>       
       Process Improvement
      body: > 
        Would you like to get the most out of your time and resources? I can help you assess and understand the current state of your business, and discover the processes that need attention the most. Measure performance, and compare it against your goals and benchmarks to identify areas of improvement. Optimize and standardize critical processes to maximize the productivity and efficiency of the work performed in your business. This will give you the ability to meet a greater demand, and consistently provide better customer experience. Book a time in my calendar and we can discuss how I can help in your problematic areas!
      icon: "/assets/images/file.png"
    - heading: >
       <span> Software </span>       
       Projects
      body: > 
        Do you need help executing your software projects? Want to know if your project plan is sound, if your team is capable of executing the project, or if your project execution is set up to deliver a top quality product on time, and within the budget? Are you making the best choice for technologies to solve your business problems; should you buy or build a product? Are your requirements defined properly, and is your design ready to move into production? All of these are important questions to consider when executing a software project. Book a call and we can discuss your project, as well as how to ensure it's setup for success!
      icon: "/assets/images/chart.png"
  contact:
    enabled:
    background: "#FAFBFD"
    image: "/assets/images/book.png"
    heading: "<span>Book a</span> Discovery Call"
    smallHeading: ""
    description: >
     All successful businesses in every industry are continually investing in improving their business processes and implementing software to stay current and get ahead of their competition.<br>
     
     Are you thinking of implementing a software into your business, or are you in the middle of a software project? Thinking of documenting or improving your business processes?<br>

     If either of those questions apply to you, book a 30 minute strategy call, and let's discuss how I can help. We will go over your current business and I will walk you through my methodology and how it can help you achieve your goals no matter where you are in the digital transformation journey.

    btnText: "yes, i want to <strong>work</strong> with <strong>neil</strong>"
    btnUrl: "#"
  about:
    enabled: true
    background: "#fff"
    heading: "<span>Why</span> ME?"
    exp: 9
    image: "/assets/images/about.png"
    description: "He is a New York Times Bestselling author. The Wall Street Journal calls him a top influencer on the web, Forbes says he is one of the top ..."
    body: | 
      <h4>yes, i want to <strong>work</strong> with <strong> neil </strong> </h4> 

      <p>He is a New York Times Bestselling author. The Wall Street Journal calls him a top influencer on the web, </p>

      <h4>yes, i want to <strong>work</strong> with <strong>neil </strong> </h4> 

      <p>He is a New York Times Bestselling author. The Wall Street Journal calls him a top influencer on the web, </p> 
  subscribe:
    enabled: true
    background: "#F8F9FC"
    heading: "Subscribe our Newslatter"
    smallHeading: "what’s next?"
    description: Get notification about tips, new product and exclusive promo news just for you.





footer:
  copyright: © 2021 Onix All rights reserved.
  about: Build custom blogs, portfolios, ecommerce stores, and more with a flexible CMS. Experience the power of HTML, CSS.
  leftcolHeading: Links
  centercolHeading:  "About"
  rightcolHeading: "Our Office"
  leftcol:
  - link: "/"
    text: Home
  - link: "/"
    text: Services
  - link: "/"
    text: How It Works
  - link: "/"
    text: Tutorial
  - link: "/"
    text: Contact
  centercol:
  - text: Partners
    link: "#home"
    pageType: "same"
  - text: Careers
    link: "#how-its-works"
    pageType: "same"
  - text: Press
    link: "#about"
    pageType: "same"
  - text: Community
    link: "#about"
    pageType: "Community"
  rightcol:
  - location: Indonesia
    address: Jl. Griya Permata Hijau no D1 Purwomartani Kalasan 543881
  - location: Tokyo
    address: 35 Mandalay Road 13–37 Mandalay Towers Singapore 308215


social:
  enable: true
  items:
  - icon: "fab fa-facebook-f"
    title: "facebook"
    link: "#"
  - icon: "fab fa-twitter"
    title: "twitter"
    link: "#"
  - icon: "fab fa-linkedin-in"
    title: "linkedin"
    link: "#"

      

 

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

# Build settings
// theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
